language: ruby
rvm:
  - 2.5.3
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # route your build to the container-based infrastructure for a faster build
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # https://github.com/typhoeus/typhoeus/issues/568
before_script:
  - npm install -g bower
  - bower install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer --assume_extension ./www
deploy:
  provider: pages # https://docs.travis-ci.com/user/deployment/pages/
  skip-cleanup: true
  github-token: $GITHUB_API  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: ./www
  on:
    branch: master
